--- 
branches: 
  - master
plugins: 
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/github"
    - assets: 
        - label: single-module-project.jar
          path: target/target/single-module-project.jar
repositoryUrl: "https://github.com/riprasad/gitub-actions-demo"
