--- 
branches: 
  - master
plugins: 
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
repositoryUrl: "https://github.com/riprasad/gitub-actions-demo"
