--- 
branches: 
  - master
plugins: 
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/github"
    - assets: 
        - label: Binary (zip)
          path: binary.zip
repositoryUrl: "https://github.com/riprasad/gitub-actions-demo"
