# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  repository_dispatch:
    types: [publish]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: riprasad
          server-password: Ri$hab01071995
          profile-id: ossrh 
      - name: Display settings.xml
        run: |
          cat /home/runner/.m2/settings.xml
          echo "MAVEN_USERNAME: ${MAVEN_USERNAME}"
          echo "MAVEN_PASSWORD: ${MAVEN_PASSWORD}"
      - name: Publish to Apache Maven Central
        run: mvn deploy 
        env:
          MAVEN_USERNAME: riprasad
          MAVEN_CENTRAL_TOKEN: Ri$hab01071995
      
