# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
on:
  repository_dispatch:
    types: [publish]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
      - name: Build maven project
        run: mvn clean install
      - name: Display settings.xml
        run: |
          pwd
          ls -a /home/
          echo "--------------------------------"
          ls -a /home/runner/.m2
          echo "--------------------------------"
          cat /home/runner/.m2/settings.xml
          
      #- name: Publish to Apache Maven Central
        #run: mvn deploy 
        #env:
        #  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        #  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      
