name: import-gpg

on:
  push:
    branches: master

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: PWD info
        run: |
          pwd
          echo "____________________________"
          ls -al
      - name: test
        run: |
           touch responsefile && curl https://api.github.com/repos/apicurio/apicurio-studio/releases/latest > responsefile
           echo "::set-env name=FILENAME::$(cat responsefile | jq '.published_at' | sed 's/"//g')"
           export ABC=$(cat responsefile | jq '.published_at' | sed 's/"//g')
           source ~/.bash_profile
           echo "----------------------"
           echo $FILENAME
           echo $ABC
           echo "----------------------"
      - name: export test
        run: |
          echo $FILENAME
          echo $ABC
