on:
  repository_dispatch:
    types: [official]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: "4.6.1"
          release_name: Release 4.6.1
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
