name: Java CI with Maven
on: 
  release:
    types: [published, created]
  repository_dispatch:
    types: [test]
jobs:
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - uses: radcortez/project-metadata-action@master
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
      - name: Get the version
        id: get_version
        run: |
          echo "${{steps.metadata.outputs.current-version}"

      
