name: Java CI with Maven
on: 
  release:
    types: [published, unpublished, created, edited, deleted, prereleased]
  repository_dispatch:
    types: [test]
jobs:
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Get the version
        id: get_version
        run: |
          echo "-----------------------------------------------------"
          echo "v${{ secrets.RELEASE_VERSION }}"
          echo "-----------------------------------------------------"
          echo "::set-env name=TAG::$(curl -s https://api.github.com/repos/riprasad/gitub-actions-demo/releases/latest| jq --raw-output '.tag_name'| cut -c 2-)"
          echo $TAG

      
