name: Java CI with Maven
on:
  pull_request:
    branches: [master]
    types: [closed]
    paths:
      - '.github/project.yaml'
  repository_dispatch:
    types: [test]
jobs:
  test-job:
    runs-on: ubuntu-18.04
    env:
      abc: "2.1.0" 
    #if: ${{github.event.pull_request.merged == true}}
    steps:
      #- uses: radcortez/project-metadata-action@master
      #  name: retrieve project metadata
      #  id: metadata
      #  with:
      #    github-token: ${{secrets.GITHUB_TOKEN}}
      #    metadata-file-path: '.github/project.yaml'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Code Checkout
        run: |
          pwd
          ls -a
          git init
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          ############################################################################################
          mvn versions:set -DnewVersion=2.1.0 -DgenerateBackupPoms=false -DprocessAllModules=true
          git add -A
          git commit -m"Update version to 2.1.0"
          git push
          
      - name: Create GitHub Release
        if: github.event_name == 'repository_dispatch'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 2.1.0###########################################
          release_name: v2.1.0  #####################################
                    
      - name: maven release ${{steps.metadata.outputs.current-version}}
        run: |
          echo ${{steps.metadata.outputs.current-version}}
          java -version
          npm --version

      
